#!/bin/sh
# AUTHOR: Mathieu Rivier
# INSTALL dotfiles
# use those commands from the Coding setup folder
source $(pwd)/files/terminal/custom/custom_messages.sh

CONFIGS=$(pwd)/files
VIM_PATH=$CONFIGS/vim
TERM_CONFIG_PATH=$CONFIGS/terminal/zshrc_config.sh

# INSTALLATION FUNCTIONS
install_f_git()
{
    # $1 = name
    # $2 = path
    # $3 = link
    if [ -d $2 ]; then
        pass_message "$1 already installed."
        return 0
    else
        git clone $3 $2
        check_success_message "$?" "installing $1"
    fi
}

link_f_git()
{
    # $1 = name
    # $2 = path
    # $3 = link
    if [ -L $1 ]; then
        rm -i $1
        if [ -e $1 ]; then
            fail_message "failed deleting the link to $1"
            return 1
        else
            pass_message "successfully deleted old link to $1"
        fi
    elif [ -e $1 ]; then
        mkdir ~/.old_confs
        mv $1 ~/.old_confs/
        check_success_message "$?" "LINK" "Moving $1 to ~/.old_confs"
    fi

    ln -s $2 $1
    check_success_message "$?" "successfully linked $2 to $1"
}

# INSTALLATION OF MY SETUP :)
termi()
{
    info_message "INST" "Terminal Config"
    STATUS=0

    # Install from remote
    # Instqll Oh-my-zsh
    install_f_git "oh-my-zsh" ~/.oh-my-zsh "git@github.com:ohmyzsh/ohmyzsh.git"

    # Instqll zsh-z
    install_f_git "zsh-z" \
                  ~/.oh-my-zsh/custom/plugins/zsh-z \
                  "git@github.com:agkozak/zsh-z.git"

    # Instqll Syntax Highlighting
    install_f_git "zsh-syntax-highlighting" \
                  ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting \
                  "git@github.com:zsh-users/zsh-syntax-highlighting.git"

    # Install autosuggestions
    install_f_git "zsh-autosuggestions" \
                  ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions \
                  "https://github.com/zsh-users/zsh-autosuggestions"

    # link
    link_f_git ~/.term_confs $CONFIGS/terminal; STATUS=$(($? + STATUS))
    link_f_git ~/.zshrc $TERM_CONFIG_PATH     ; STATUS=$(($? + STATUS))

    info_message "SOUR" "Sourcing ~/.zshrc"
    source ~/.zshrc

    end_message $STATUS "term profile"
}

vimi()
{
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    info_message "INST" "Installing Vim Config"
    STATUS=0

    link_f_git ~/.vim $VIM_PATH/.vim    ; STATUS=$(($? + STATUS))
    link_f_git ~/.vimrc $VIM_PATH/.vimrc; STATUS=$(($? + STATUS))

    end_message $STATUS "installing vim config"
}

giti()
{
    STATUS=0
    link_f_git ~/.gitconfig $CONFIGS/git/gitconfig; STATUS=$(($? + STATUS))
    link_f_git ~/.gitignore $CONFIGS/git/gitignore ; STATUS=$(($? + STATUS))

    end_message  $STATUS "installing git config"
    info_message "Please replace your git name , mail and username"
    echo "Using the following command:"
    echo "git config --global user.name YOUR_NAME"
    echo "git config --global user.email bla@bla.com"
    echo "git config --global user.username YOUR_PSEUDO"
}

install_brew()
{
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}
